### ISSUE TITLE
Tags arent being synced to git

### ISSUE THREAD

**Issue by justlevine** [leftstick/vscode-git-tags#16]
For whatever reason, when I create a tag, it appears locally but it doesnt get synced by vscode to github.

Commits made after the tag are created are synced to github fine. and running `git push --tags` from the cli works fine. Its just the sync button thats broken.

I'm assuming its related to https://github.com/Microsoft/vscode/issues/48211

Ideas?

**Comment by leftstick** [comment]
@geforcesong George, could you please take a look at this issue?

**Comment by geforcesong** [comment]
Hi @justlevine,

I tried it, it works on my end. Please make sure you selected the right command. It is the 2nd one on my vscode. Otherwise, i think vscode provided the default tag manager, it will add locally, then you need push it manually.

<img width="919" alt="Screen Shot 2019-09-16 at 3 23 00 PM" src="https://user-images.githubusercontent.com/5226567/64997549-f0038500-d895-11e9-9ac7-a9338dda50c9.png">

**Comment by justlevine** [comment]
🤦‍♀️ that would explain it. Thanks!

**Comment by leftstick** [comment]
@geforcesong nice one, George, thanks
